### ISSUE TITLE
General OAuth2 support?

### ISSUE THREAD

**Issue by alindgren** [matvelloso/AuthBot#11]
This looks great! I'm looking for authenticating with other OAuth2 services and was wondering if you plan to support that in the future.

Thanks,

Alex

**Comment by matvelloso** [comment]
Alex, Azure AD has a feature called "B2C" which lets you bring your own identity from things like Google, Facebook, LinkedIn and MSA. I'm close to add support to that into AuthBot which would open many scenarios at once without having to custom code each one. Somebody else is also adding Visual Studio Online support to it. So we're slowly getting there

**Comment by alindgren** [comment]
Thanks!
