### ISSUE TITLE
Unable to find a constructor to use for type Microsoft.Bot.Builder.Dialogs.ResumptionCookie

### ISSUE THREAD

**Issue by OmShrivastava** [matvelloso/AuthBot#14]
Hi 

I am trying to authenticate my Bot Builder  V3.2 app with AzureAD but after login not getting Magic number always getting error like 
{
  "message": "An error has occurred.",
  "exceptionMessage": "Unable to find a constructor to use for type Microsoft.Bot.Builder.Dialogs.ResumptionCookie. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'address'.",
  "exceptionType": "Newtonsoft.Json.JsonSerializationException",
  "stackTrace": "   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)\r\n   at Microsoft.Bot.Builder.Dialogs.UrlToken.Decode[T](String token)\r\n   at AuthBot.Controllers.OAuthCallbackController.<OAuthCallback>d__3.MoveNext()"
}

**Comment by OmShrivastava** [comment]
Hi 
I have found solution 
I was using Bot.Builder v_3.2.1 after I have degrade to Bot.Builder v_3.2.0 issue is resolved.

I think there is a comparability issue between Bot.Builder v_3.2.1 and AuthBot v_3.1.1

**Comment by ejadib** [comment]
@OmShrivastava, in the latest version of Bot Builder there was a change around the ResumptionCookie and that's the root cause of the serialization issue. The issue was already reported to the bot framework team. I might submit at PR to the AzureBot, changing the dependency on ResumptionCookie to individual parameters
