### ISSUE TITLE
Breaking change in BotBuilder 3.3.0

### ISSUE THREAD

**Issue by duckwaffle** [matvelloso/AuthBot#17]
Hi, I know the code isn't being maintained on this repo any more, but it looks like the move of the repo wasn't finished because its not possible to raise issues on the MicrosoftDX fork.

v3.3.0 of BotBuilder for C# has changed the constructor for ResumptionCookie, it now takes Address as a POCO instead of as a collection of properties.

Additionally, wouldn't it be better to use the GZipSerialize and GZipDeserialize methods to pass the resumption cookie around, rather than encoding it manually?

**Comment by matvelloso** [comment]
Sorry, just fixed the issue block on the other repo, feel free to use that one moving forward. Also pushed a new version of the nuget package that should unblock you
