### ISSUE TITLE
Cannot "quit" the authentication dialog

### ISSUE THREAD

**Issue by ejadib** [matvelloso/AuthBot#5]
Once you instantiate the AzureAuthDialog there is not way to quit and so you enter in an infinite loop where the Bot just answer _"You must be authenticated before you can proceed. Please, click here to log into your account."_

Considering handling messages like "Quit", "Exit", "Stop", "Cancel" and perform a context.Done()

**Comment by matvelloso** [comment]
Just got this fixed today

**Comment by dtzar** [comment]
Verified this works, thanks!  Suggestion would be to modify the [auth message](https://github.com/matvelloso/AuthBot/blob/20ba277c5de49a0bddc301c70c94f14898ff5126/AuthBot/Dialogs/AzureAuthDialog.cs#L100) and let people know they can type quit/cancel/etc to stop trying to login.
