### ISSUE TITLE
Callback code wont display in IE (most of the time)

### ISSUE THREAD

**Issue by ADefWebserver** [matvelloso/AuthBot#6]
This code in "\AuthBot\AuthBot\Controllers\OAuthCallbackController.cs":
```
var resp = new HttpResponseMessage(HttpStatusCode.OK);
resp.Content = new StringContent($"<html><body>Almost done! Please copy this number and paste it back to your chat so your authentication can complete: {magicNumber}.</body></html>", System.Text.Encoding.UTF8, @"text/html");
return resp;
```
Causes IE to hang because it tries to show a file (that is not there). The code works fine in Chrome and Firefox. It also works fine in IE if you are in debug mode and slowly step through the code.
I made a video:
https://www.dropbox.com/s/xztaprsff15qx6l/AuthBotError.mp4?dl=0

**Comment by matvelloso** [comment]
Michael. When you see that JSON happening in IE this means an exception happened on the backend. If you try again without stopping the debugger, even on IE, it will work. That behavior only happens with the emulator. Once you publish to the actual website and use another channel, the problem, that won't happen. It's an issue we only have with the emulator and are trying to figure out why

**Comment by ADefWebserver** [comment]
Thank you so much!
I will open another thread about some ideas I had on the 'magic number' but I am satisfied that this is not a show stopper.
