### ISSUE TITLE
Does the user need to type in the 'MagicNumber" ?

### ISSUE THREAD

**Issue by ADefWebserver** [matvelloso/AuthBot#7]
My understanding is that we need it because we are afraid of allowing a user to use another user’s identity token (for example when the Bot is participating in a group conversation – other users could click on the link) 

After reading the code (assuming I am getting this right), it appears it works like this:

1. User is not logged in, so we create a “resumptionCookie” (so we know who this authentication is for) and then create a URL to send them to Active Directory to log in (tacking the “resumptionCookie” onto the payload. 
2. User logs and they are sent back to our OAuthCallbackController. We know who the user is because we are able to ‘unpack’ the “resumptionCookie” as it contains the user id. However, we now create a ‘magic number’ (just a random number) and store that in Bot User Data using “SetUserDataAsync” along with the Active Directory authentication token that was passed to OAuthCallbackController (the Active Directory authentication token is what we are really after. It is what will allow us to do things like allow the user to view their OneDrive).
3. We then display this magic number to the user and ask them to enter it into the chat window. Only when we detect that the user we asked to enter the magic number, has entered the correct magic number, do we allow the user to use the Active Directory authentication token (to do things like look though their OneDrive)

My question, can we store the ‘magic number’ in the user data before we send them the link to log into Active Directory?

Even if the wrong person clicked on the link and logged in, we would still only allow that Active Directory authentication token to be assigned to the user we intended it to be used by.

**Comment by matvelloso** [comment]
If you did that, then we would be back to the original problem: I can't prove who clicked at that link was indeed the intended person we wanted to. What you can do though is on a custom channel (a web site, a custom app) you could authenticate the user outside the bot and then reuse it within the bot, so none of this would be required.

**Comment by ADefWebserver** [comment]
If the wrong user clicks on the link (meaning a user for whom we did not first store a 'magic number' in the user's Bot data), wouldn't the "resumptionCookie" contain a magic number that is not stored in the user's Bot data? 

If so, we would not allow the Active Directory authentication token to be used, so security would be enforced. 

If I am wrong then, yes you're right it is a security risk.

**Comment by matvelloso** [comment]
There's nothing that binds the chat user with the AD user. With we embed this into the link itself, then nothing will tell me user A and not user B clicked on it. They both can click and authenticate. One of them needs to bring me back a proof that they did it into the chat.

**Comment by ADefWebserver** [comment]
Oh so the “resumptionCookie” (that is tacked onto the payload of the Active Directory request) does not contain the userId that we 'intended' to click on the link? If not, can we put that in the “resumptionCookie”?

**Comment by matvelloso** [comment]
All that cookie does is giving me the ability to resume the chat with that user from that web page. But neither that cookie or the bot itself knows what was supposed to be the AAD user to be tied to that chat session. So anything you put in that link will be visible to all users in that chat session and therefore any of them can click or even tamper that link in any way they want. That alone doesn't offer us enough guarantee of a secure authentication back to the bot.

**Comment by ADefWebserver** [comment]
Thank you for taking the time to fully explain this. Hopefully you can just point the next person to this thread :) 

I will try to do an example where I log a user into Azure AD first and then connect to the Bot and set the Active Directory authentication token.
